// src/lib/seedData.ts
// Initial data seeded from Sokxay_Plus_Issue.xlsx
import type { IssueFormData } from "./issueService";

export const INITIAL_ISSUES: IssueFormData[] = [
  {
    no: 1,
    category: "Splus Portal - Topup",
    description:
      "ອັບເດດ Splus Portal - ເພີ່ມ filter ໃຫ້ສາມາດເບິງຂໍ້ມູນ Pro topup ຍ້ອນຫຼັງ ແລະ ລາຍງານທີ່ສະແດງໃຫ້ ເຫັນ ໂຄຕ້າທີ່ຕັ້ງ ແລະ ຍອດທີ່ໃຊ້ຕົວຈິງ",
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 2,
    category: "Splus Portal - Topup",
    description:
      'Pro ຕື່ມ 20 ໄດ້ 30 - ລາຍການ ທີ່ Error ຊ້ວງໂປຣ ເວລາ "ຕື່ມເງິນຄືນ" ແມ່ນສໍາເລັດ ແຕ່ລາຍການຕົ້ນ ສ່ວນລາຍການໂປຣ ບໍສໍາເລັດ',
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 3,
    category: "Splus Portal - Topup",
    description:
      'ສ້າງເມນູ ປ່ຽນສະຖານະລາຍການ Error (ທີ່ກວດພົບວ່າ ສໍາເລັດເບື້ອງໂທລະຄົມ) ໃຫ້ເປັນສະຖານນະ DONE_TELCO ເພື່ອບໍ່ໃຫ້ ສາມາດກົດ "ລອງຕື່ມໃໝ່" ໄດ້ອີກ',
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 4,
    category: "JDB",
    description:
      "ຊື້ເລກ ຕັດເງິນ ແຕ່ບໍ່ໄດ້ຮັບບິນ ແລະ ບິນຫວຍຢູ່ Lotlink ເປັນ Active ເຊິ່ງສົ່ງຜົນຕໍ່ລາຍງານ ບິນສໍາເລັດ ແລະ ກໍລະນີ ຖືກເງິນລາງວັນ ສົ່ງຜົນຕໍ່ລາຍງານເງິນລາງວັນ",
    reportedDate: "2026-02-13",
    resolvedDate: "2026-02-24",
    note: "",
    status: "done",
  },
  {
    no: 5,
    category: "JDB",
    description: "ບໍ່ໄດ້ຮັບສິດ",
    reportedDate: "2026-02-13",
    resolvedDate: "2026-02-24",
    note: "",
    status: "done",
  },
  {
    no: 6,
    category: "JDB",
    description: "Refund ( JDB ກໍາລັງດໍາເນີນການ ຈະອັບຂຶ້ນ prod ວັນຈັນ 23-02-2026)",
    reportedDate: "2026-02-19",
    resolvedDate: "2026-02-24",
    note: "",
    status: "done",
  },
  {
    no: 7,
    category: "Splus Portal - ຫວຍ",
    description: "ບໍ່ມີ ເມນູ ກວດຂໍ້ມູນບິນຫວຍ ຢູ່ ລະບົບ SPlus (production)",
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 8,
    category: "Splus Portal - ຫວຍ",
    description: "ບໍ່ມີ ເມນູ ກວດ ແລະ refund ເງິນຄືນໃຫ້ ລູກຄ້າ",
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 9,
    category: "SPIN",
    description: "ເມນູ ກວດ ສິດ ແລະ ການນໍາໃຊ້ສິດ",
    reportedDate: "2026-02-13",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 10,
    category: "SPIN",
    description:
      "ສະແດງ ແລະ ປ່ຽນ ເລກບັນຊີ ຮອງຮັບ ເງິນລາງວັນ (ນອກຈາກລາງວັນຫວຍ ເນື່ອງຈາກ ລະບົບຈະເອົາບັນຊີ ຕາມບິນທີ່ຊື້)",
    reportedDate: "2026-02-13",
    resolvedDate: "2026-02-22",
    note: "",
    status: "done",
  },
  {
    no: 11,
    category: "SPIN",
    description:
      "ເມນູ ສະແດງ ລາຍການ SPIN ທີ່ໄດ້ຮັບເງິນລາງວັນ (ລູກຄ້າບາງລາຍກົດຫຼາຍຄັ້ງ ແລະ ບໍ່ສາມາດຍ້ອນເບິງລາຍການທີ່ຖືກລາງວັນ ແຕ່ບໍ່ໄດ້ຮັບເງິນ)",
    reportedDate: "2026-02-13",
    resolvedDate: "2026-02-28",
    note: "",
    status: "done",
  },
  {
    no: 12,
    category: "SPIN",
    description: "ເພີ່ມ ເລກ reference SPIN ເວລາ ກົດເຂົ້າເບິງລາງວັນ ວົງລໍ້ໂຊກໄຊ",
    reportedDate: "2026-02-24",
    resolvedDate: "2026-02-28",
    note: "",
    status: "done",
  },
  {
    no: 13,
    category: "ບັນຊີຮັບລາງວັນ",
    description: "ເມນູ ກວດ ແລະ ປ່ຽນ ເລກບັນຊີຮັບເງິນລາງວັນ",
    reportedDate: "2026-02-13",
    resolvedDate: "2026-02-22",
    note: "",
    status: "done",
  },
  {
    no: 14,
    category: "ແອັບ Sokxay One Plus",
    description:
      'ເພີ່ມເມນູ "ແຈ້ງບັນຫາ", ລູກຄ້າສາມາດເລືອກວ່າ ແຈ້ງບັນຫາ ກ່ຽວກັບ ຫວຍ, topup, ຈອງປີ້ເຮືອບິນ',
    reportedDate: "2026-02-19",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 15,
    category: "ການເບີກຈ່າຍລາງວັນ LDB",
    description:
      'ໃຊ້ເຄື່ອງໝາຍ "|" ຂັ້ນເນື້ອໃນ ໂດຍສະເພາະ ບິນຫວຍ ງວດ ແລະ txn_ID (ແຈ້ງວ່າໄດ້ແກ້ໄຂແລ້ວ ແຕ່ຢູ່ ສະເຕັດເມັ້ນຂອງ LDB ຍັງບໍ່ໄດ້)',
    reportedDate: "2026-02-19",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 16,
    category: "REFUND ເງິນ LDB",
    description: "ຂໍ້ມູນ ງວດ ບິນ ບໍ່ເຫັນ ແລະ ເຫັນແຕ່ TXN_ID",
    reportedDate: "2026-02-19",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 17,
    category: "REFUND ເງິນ LDB",
    description: "Refund ແບບ Auto",
    reportedDate: "2026-02-19",
    resolvedDate: "2026-02-24",
    note: "",
    status: "done",
  },
  {
    no: 18,
    category: "REFUND ເງິນ LDB",
    description: 'ໃຊ້ເຄື່ອງໝາຍ "|" ຂັ້ນເນື້ອໃນ ໂດຍສະເພາະ ບິນຫວຍ ງວດ ແລະ txn_ID',
    reportedDate: "2026-02-19",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 19,
    category: "Splus Portal - ຫວຍ",
    description: "ສ້າງເມນູ ກວດ ບິນຫວຍ ທີ່ຖືກລາງວັນ ແລະ ສະຖານະການເບີກຈ່າຍ ຂອງບິນຫວຍນັ້ນ",
    reportedDate: "2026-02-27",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
  {
    no: 20,
    category: "Splus Portal - ຈອງປີ້ເຮືອບິນ",
    description:
      "ເພີ່ມຄຳອະທິບາຍໃນຮູບແບບ Tooltip ຫຼື popup ສຳລັບຊ່ອງປ້ອນຂໍ້ມູນໃນຟອມຈອງປີ້ເຮືອບິນ + ເພີ່ມເວລາຟອມຈອງປີ້ເຮືອບິນເປັນ 10 ນາທີ",
    reportedDate: "2026-03-16",
    resolvedDate: "",
    note: "",
    status: "pending",
  },
];
